### ISSUE TITLE
Create favicon for ermekeilkarree.de

### ISSUE THREAD

**Issue by danielappelt** [Ermekeilinitiative/ermekeil-issues#1]
The current favicon resides in assets/images/icons/ in our wordpress theme.

**Comment by Tinendo** [comment]
Done!

Please take a look at the favicon.ico and confirm it. It's a modification of the Ermekeilinitiative e. V. Logo for a size of 16px x 16px. I prefer this style over a fine-art Pixel by Pixel design.
