### ISSUE TITLE
Hide last event on front page (Desktop)

### ISSUE THREAD

**Issue by Tinendo** [Ermekeilinitiative/ermekeil-issues#16]
Hide the last event of "Die nächsten Termine und Veranstaltungen" on the front page via CSS (only Desktop-Version / Large-Version).

**Comment by Tinendo** [comment]
Done!

See assets/scss/ermekeil.scss row 602.

**Comment by danielappelt** [comment]
See http://foundation.zurb.com/sites/docs/media-queries.html for imitating Foundation break-points using CSS.

Philosophical side note: Showing less information on a larger screen is not very intuitive.

**Comment by Tinendo** [comment]
Alternative solution: We could show 12 events, so the number of events is divisible by the number 2.

**Comment by danielappelt** [comment]
In theory, it should be enough to even start with only 6 events. This should easily cover the whole coming week. If we see later on that it is not enough we can go up to 12.

**Comment by Tinendo** [comment]
I agree. So I'm going to remove the CSS and now the issue is all yours again. ;-)
